const list = [
    {
      id: 1,
      title: "Veg Biryani",
      hotel: "Shiv Shakti Restaurant",
      price: 90,
      img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/09/veg-biryani-vegetable-biryani.jpg",
      amount: 1,
     
    },
    {
      id: 2,
      title: "Paper Dosa",
      hotel: "Celebrations",
      price: 60,
      img: "https://i.pinimg.com/736x/a6/e9/bd/a6e9bdb8fd56e588af99b9d7d99d43b8.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Masala Dosa",
      hotel: "Happy Dhaba",
      price: 80,
      img: "https://palatesdesire.com/wp-content/uploads/2022/09/Mysore-masala-dosa-recipe@palates-desire.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Chhese Pizza",
      hotel: "Eat and Joy",
      price: 100,
      img: "https://preppykitchen.com/wp-content/uploads/2021/10/Cheese-Pizza-Recipe-Card-500x375.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Chhese Burger",
      hotel: "Eat and Joy",
      price: 70,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpVJm8DPj-rkK10RQCQCvxEr_xj1f3j01b-A&s",
      amount: 1,
    },
    {
      id: 6,
      title: "Matar Paneer",
      hotel: "Happy Palace",
      price: 120,
      img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/03/matar-paneer-480x270.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: " Naan",
      hotel: "Happy Palace",
      price: 30,
      img: "https://www.vegrecipesofindia.com/wp-content/uploads/2022/12/garlic-naan-3.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Khichdi",
      hotel: "Sanjay Hotel",
      price: 60,
      img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/07/khichdi-recipe.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Chocolate Milkshake",
      hotel: "Baba Ka Dhaba",
      price: 60,
      img: "https://www.willcookforfriends.com/wp-content/uploads/2017/01/Decadent-Chocolate-Milkshake-Youd-Never-Know-Is-Healthy-hi-res-web-1B-683x1024.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Lassi",
      hotel: "Baba Ka Dhaba",
      price: 50,
      img: "https://somethingiscooking.com/wp-content/uploads/2017/04/Lassi-1.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Grilled Sandwich",
      hotel: "Metro Eateries",
      price: 40,
      img: "https://wiproappliances.com/cdn/shop/articles/Veg_grilled_cheese_sandwich.jpg?v=1714126819",
      amount: 1,
    },
    {
      id: 12,
      title: "Chhole Bhature",
      hotel: "Welcome Pure Veg Restaurant",
      price: 130,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqFHMCZ7CnPo5NEqxOwyckoODeiRyLxYmiHg&s",
      amount: 1,
    },
];

export default list;